export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'
export const SET_DURATION = 'SET_DURATION'
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'
export const SET_PAGE_FULL_SCREEN = 'SET_PAGE_FULL_SCREEN'
